# 配置项目端口 与 访问路径
server:
  port: 10010
  servlet:
    context-path: /zombie
  tomcat:
    uri-encoding: utf-8
    # 请求最大线程数
    max-threads: 1000
    # 最大空闲线程数
    min-spare-threads: 30
    # 连接超时时间
  connection-timeout: 5000ms

# mysql 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost/zombieblog
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    # 配置数据源
    # type: com.alibaba.druid.pool.DruidDataSourcemaxActive
    # 初始化大小，最小，最大连接数
    initialSize: 5
    minIdle: 1
    maxActive: 100
    # 配置获取连接超时最大等待时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 验证sql，校验数据库是否连接正常
    validationQuery: SELECT 1 FROM DUAL
    # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    testOnBorrow: false
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    # 是否缓存preparedStatement，也就是PSCache。比如说oracle 提升性能大。在mysql下建议关闭。
    poolPreparedStatements: false
    # 配置扩展插件 监控统计用的filter:stat日志用的filter:log4j防御sql注入的filter:wall
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000"
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true


# 配置mybatis mapper 文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.rtm.zombie.module.blog.core.entity
